In [1]:
"""Jupyter Notebook'ta ya da Google Colab'de şu sorulara cevap verin:

Ankete kaç kişi katıldı?
Kaç kişi tüm soruları yanıtladı?
Katılımcıların çalışma deneyimleriyle (WorkExp) ilgili merkezi eğilim ölçüleri nelerdir?
Kaç kişi uzaktan çalışıyor?
Katılımcıların yüzde kaçı Python ile programlama yapıyor?
Kaç kişi online kurslar ile programlama öğrendi?
Ülkelere göre gruplanmış ve Python ile programlama yapan katılımcılar arasında, 
her ülkede ortalama ve medyan yıllık tazminat (ConvertedCompYearly) ne kadardır?
En yüksek tazminata sahip 5 katılımcının eğitim seviyeleri nelerdir?

Bonus Sorular:

Her yaş grubunda Python ile programlama yapan katılımcıların yüzdesi nedir?
Yıllık tazminatı en yüksek %25'lik dilimde olan ve uzaktan çalışan kişilerin yer aldığı en yaygın endüstriler nelerdir?"""

"Jupyter Notebook'ta ya da Google Colab'de şu sorulara cevap verin:\n\nAnkete kaç kişi katıldı?\nKaç kişi tüm soruları yanıtladı?\nKatılımcıların çalışma deneyimleriyle (WorkExp) ilgili merkezi eğilim ölçüleri nelerdir?\nKaç kişi uzaktan çalışıyor?\nKatılımcıların yüzde kaçı Python ile programlama yapıyor?\nKaç kişi online kurslar ile programlama öğrendi?\nÜlkelere göre gruplanmış ve Python ile programlama yapan katılımcılar arasında, \nher ülkede ortalama ve medyan yıllık tazminat (ConvertedCompYearly) ne kadardır?\nEn yüksek tazminata sahip 5 katılımcının eğitim seviyeleri nelerdir?\n\nBonus Sorular:\n\nHer yaş grubunda Python ile programlama yapan katılımcıların yüzdesi nedir?\nYıllık tazminatı en yüksek %25'lik dilimde olan ve uzaktan çalışan kişilerin yer aldığı en yaygın endüstriler nelerdir?"

In [2]:
### import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df0 = pd.read_csv(r"C:\Users\vz\Desktop\goit python çalışmalar\4. ödev\stack-overflow-developer-survey-2024\survey_results_public.csv")
df0.head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

In [4]:
df = df0.copy()
df

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65432,65433,I am a developer by profession,18-24 years old,"Employed, full-time",Remote,Apples,Hobby;School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","On the job training;School (i.e., University, ...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65433,65434,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65434,65435,I am a developer by profession,25-34 years old,"Employed, full-time",In-person,Apples,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Stack Overflow;Social ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65435,65436,I am a developer by profession,18-24 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Profe...,"Secondary school (e.g. American high school, G...",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
65436,65437,I code primarily as a hobby,18-24 years old,"Student, full-time",NaN,Apples,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65437 entries, 0 to 65436
Columns: 114 entries, ResponseId to JobSat
dtypes: float64(13), int64(1), object(100)
memory usage: 56.9+ MB

In [6]:
df.isnull().sum()

ResponseId                 0
MainBranch                 0
Age                        0
Employment                 0
RemoteWork             10631
                       ...
JobSatPoints_11        35992
SurveyLength            9255
SurveyEase              9199
ConvertedCompYearly    42002
JobSat                 36311
Length: 114, dtype: int64

In [7]:
# Tamamen null olan satır sayısı
null_row_count = df.isnull().all(axis=1).sum()

In [8]:
# Tamamen null olan sütun sayısı
null_column_count = df.isnull().all(axis=0).sum()

In [9]:
print(f"Tamamen null olan satır sayısı: {null_row_count}")
print(f"Tamamen null olan sütun sayısı: {null_column_count}")

Tamamen null olan satır sayısı: 0
Tamamen null olan sütun sayısı: 0

In [10]:
#Ankete kaç kişi katıldı?

df.shape

df.shape[0]

65437

In [11]:
#Kaç kişi tüm soruları yanıtladı?

df.notnull().all(axis=1).sum()

0

In [12]:
df.isnull().any(axis=1).sum()

65437

In [13]:
#Katılımcıların çalışma deneyimleriyle (WorkExp) ilgili merkezi eğilim ölçüleri nelerdir?

print(df.columns.to_list())

['ResponseId', 'MainBranch', 'Age', 'Employment', 'RemoteWork', 'Check', 'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline', 'TechDoc', 'YearsCode', 'YearsCodePro', 'DevType', 'OrgSize', 'PurchaseInfluence', 'BuyNewTool', 'BuildvsBuy', 'TechEndorse', 'Country', 'Currency', 'CompTotal', 'LanguageHaveWorkedWith', 'LanguageWantToWorkWith', 'LanguageAdmired', 'DatabaseHaveWorkedWith', 'DatabaseWantToWorkWith', 'DatabaseAdmired', 'PlatformHaveWorkedWith', 'PlatformWantToWorkWith', 'PlatformAdmired', 'WebframeHaveWorkedWith', 'WebframeWantToWorkWith', 'WebframeAdmired', 'EmbeddedHaveWorkedWith', 'EmbeddedWantToWorkWith', 'EmbeddedAdmired', 'MiscTechHaveWorkedWith', 'MiscTechWantToWorkWith', 'MiscTechAdmired', 'ToolsTechHaveWorkedWith', 'ToolsTechWantToWorkWith', 'ToolsTechAdmired', 'NEWCollabToolsHaveWorkedWith', 'NEWCollabToolsWantToWorkWith', 'NEWCollabToolsAdmired', 'OpSysPersonal use', 'OpSysProfessional use', 'OfficeStackAsyncHaveWorkedWith', 'OfficeStackAsyncWantToWorkWith', 'OfficeStackAsyncAdmired', 'OfficeStackSyncHaveWorkedWith', 'OfficeStackSyncWantToWorkWith', 'OfficeStackSyncAdmired', 'AISearchDevHaveWorkedWith', 'AISearchDevWantToWorkWith', 'AISearchDevAdmired', 'NEWSOSites', 'SOVisitFreq', 'SOAccount', 'SOPartFreq', 'SOHow', 'SOComm', 'AISelect', 'AISent', 'AIBen', 'AIAcc', 'AIComplex', 'AIToolCurrently Using', 'AIToolInterested in Using', 'AIToolNot interested in Using', 'AINextMuch more integrated', 'AINextNo change', 'AINextMore integrated', 'AINextLess integrated', 'AINextMuch less integrated', 'AIThreat', 'AIEthics', 'AIChallenges', 'TBranch', 'ICorPM', 'WorkExp', 'Knowledge_1', 'Knowledge_2', 'Knowledge_3', 'Knowledge_4', 'Knowledge_5', 'Knowledge_6', 'Knowledge_7', 'Knowledge_8', 'Knowledge_9', 'Frequency_1', 'Frequency_2', 'Frequency_3', 'TimeSearching', 'TimeAnswering', 'Frustration', 'ProfessionalTech', 'ProfessionalCloud', 'ProfessionalQuestion', 'Industry', 'JobSatPoints_1', 'JobSatPoints_4', 'JobSatPoints_5', 'JobSatPoints_6', 'JobSatPoints_7', 'JobSatPoints_8', 'JobSatPoints_9', 'JobSatPoints_10', 'JobSatPoints_11', 'SurveyLength', 'SurveyEase', 'ConvertedCompYearly', 'JobSat']

In [14]:
df[["WorkExp"]].describe()

            WorkExp
count  29658.000000
mean      11.466957
std        9.168709
min        0.000000
25%        4.000000
50%        9.000000
75%       16.000000
max       50.000000

In [15]:
#Kaç kişi uzaktan çalışıyor?

df["RemoteWork"].value_counts()

RemoteWork
Hybrid (some remote, some in-person)    23015
Remote                                  20831
In-person                               10960
Name: count, dtype: int64

In [16]:
df[df["RemoteWork"] == "Remote"].count()

ResponseId             20831
MainBranch             20831
Age                    20831
Employment             20831
RemoteWork             20831
                       ...
JobSatPoints_11        11186
SurveyLength           18352
SurveyEase             18370
ConvertedCompYearly     9591
JobSat                 11103
Length: 114, dtype: int64

In [17]:
df[df["RemoteWork"] == "Remote"]["RemoteWork"].shape[0]

20831

In [18]:
#Katılımcıların yüzde kaçı Python ile programlama yapıyor?

df[["LanguageHaveWorkedWith"]]

                                  LanguageHaveWorkedWith
0                                                    NaN
1      Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...
2                                                     C#
3      C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...
4                C++;HTML/CSS;JavaScript;Lua;Python;Rust
...                                                  ...
65432                                                NaN
65433                                                NaN
65434                                                NaN
65435           C;C++;Go;Lua;Objective-C;Python;Rust;SQL
65436   C;HTML/CSS;Java;JavaScript;PHP;Python;TypeScript

[65437 rows x 1 columns]

In [19]:
import re

In [20]:
df["LanguageHaveWorkedWith"]

0                                                      NaN
1        Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...
2                                                       C#
3        C;C++;HTML/CSS;Java;JavaScript;PHP;PowerShell;...
4                  C++;HTML/CSS;JavaScript;Lua;Python;Rust
                               ...
65432                                                  NaN
65433                                                  NaN
65434                                                  NaN
65435             C;C++;Go;Lua;Objective-C;Python;Rust;SQL
65436     C;HTML/CSS;Java;JavaScript;PHP;Python;TypeScript
Name: LanguageHaveWorkedWith, Length: 65437, dtype: object

In [21]:
pattern = r';?\s*(Python)\s*;?'
df["WorkedPython"] = df["LanguageHaveWorkedWith"].str.extract(pattern)

In [22]:
df["WorkedPython"].value_counts(dropna=False)

WorkedPython
NaN       34642
Python    30795
Name: count, dtype: int64

In [23]:
python_count = df["WorkedPython"].notna().sum()
total_count = df.shape[0]
python_percentage = (python_count / total_count) * 100
print(f"Katılımcıların yüzde {python_percentage:.2f}'si Python ile programlama yapıyor.")

Katılımcıların yüzde 47.06'si Python ile programlama yapıyor.

In [24]:
#Kaç kişi online kurslar ile programlama öğrendi?
df.sample(20)

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat,WorkedPython
40603,40604,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","School (i.e., University, College, etc)",NaN,...,25.0,10.0,0.0,0.0,5.0,Appropriate in length,Easy,101910.0,7.0,NaN
40380,40381,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects,Some college/university study without earning ...,Books / Physical media;On the job training;Oth...,Technical documentation;Blogs;Stack Overflow;A...,...,20.0,20.0,20.0,0.0,0.0,Too long,Easy,70584.0,8.0,Python
53064,53065,I am a developer by profession,18-24 years old,"Student, part-time",NaN,Apples,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18444,18445,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Professional development or self-paced learnin...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",On the job training;Other online resources (e....,Technical documentation;Written Tutorials;Stac...,...,0.0,0.0,0.0,0.0,0.0,Appropriate in length,Neither easy nor difficult,NaN,7.0,Python
26259,26260,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN,Python
43987,43988,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,15.0,15.0,20.0,0.0,0.0,Appropriate in length,Easy,NaN,8.0,NaN
18056,18057,I am a developer by profession,18-24 years old,"Employed, full-time;Student, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Professional development or self-paced l...,Primary/elementary school,Books / Physical media;Colleague;On the job tr...,Technical documentation;Stack Overflow;AI,...,10.0,10.0,10.0,10.0,10.0,Appropriate in length,Easy,NaN,10.0,NaN
60934,60935,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby;Bootstrapping a business,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,20.0,20.0,0.0,20.0,0.0,Appropriate in length,Easy,NaN,7.0,Python
11085,11086,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby;School or academic work;Professional dev...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,Too long,Easy,76000.0,NaN,NaN
12159,12160,I am a developer by profession,18-24 years old,"Employed, full-time",In-person,Apples,Professional development or self-paced learnin...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;On the job training;Sch...,NaN,...,0.0,0.0,0.0,0.0,0.0,Too long,Easy,NaN,6.0,NaN
17411,17412,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Books;Written Tutorial...,...,20.0,8.0,30.0,5.0,2.0,Appropriate in length,Neither easy nor difficult,84076.0,3.0,NaN
64904,64905,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","School (i.e., University, College, etc);Coding...",NaN,...,90.0,0.0,70.0,0.0,0.0,Appropriate in length,Neither easy nor difficult,NaN,7.0,NaN
50290,50291,I am a developer by profession,35-44 years old,"Employed, part-time","Hybrid (some remote, some in-person)",Apples,I don’t code outside of work,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,25.0,10.0,20.0,10.0,0.0,Appropriate in length,Easy,NaN,10.0,Python
15284,15285,"I am not primarily a developer, but I write co...",18-24 years old,"Student, full-time;Employed, part-time",In-person,Apples,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorials,...,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Difficult,NaN,NaN,Python
13967,13968,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation,...,0.0,0.0,0.0,0.0,0.0,Appropriate in length,Neither easy nor difficult,15553.0,9.0,Python
32565,32566,I am a developer by profession,55-64 years old,"Employed, full-time;Independent contractor, fr...",Remote,Apples,Hobby;Professional development or self-paced l...,"Associate degree (A.A., A.S., etc.)",On the job training;Other online resources (e....,Technical documentation;Blogs;Books;Written Tu...,...,20.0,50.0,10.0,0.0,10.0,Too long,Neither easy nor difficult,150369.0,8.0,NaN
6829,6830,"I am not primarily a developer, but I write co...",25-34 years old,"Employed, full-time",Remote,Apples,Contribute to open-source projects;Professiona...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,0.0,5.0,0.0,0.0,20.0,Appropriate in length,Easy,NaN,5.0,NaN
40503,40504,I am a developer by profession,35-44 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Professional development or self-paced l...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Stack Over...,...,40.0,30.0,10.0,10.0,10.0,Appropriate in length,Neither easy nor difficult,80555.0,8.0,Python
40134,40135,"I am not primarily a developer, but I write co...",45-54 years old,"Not employed, but looking for work",NaN,Apples,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;On the job training;Oth...,Technical documentation;Books;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN,NaN
50644,50645,I code primarily as a hobby,65 years or older,Retired,NaN,Apples,NaN,"Associate degree (A.A., A.S., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Stack Overflow;Social ...,...,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN,NaN

In [25]:
df["LearnCode"].value_counts(dropna= False)

LearnCode
NaN                                                                                                                                                                                                 4949
Other online resources (e.g., videos, blogs, forum, online community)                                                                                                                               3674
Books / Physical media;Other online resources (e.g., videos, blogs, forum, online community)                                                                                                        2493
Other online resources (e.g., videos, blogs, forum, online community);School (i.e., University, College, etc)                                                                                       2362
Books / Physical media;Other online resources (e.g., videos, blogs, forum, online community);Online Courses or Certification                                                                        2286
                                                                                                                                                                                                    ...
On the job training;Friend or family member;Other (please specify):                                                                                                                                    1
Books / Physical media;Colleague;On the job training;School (i.e., University, College, etc);Coding Bootcamp;Friend or family member                                                                   1
Books / Physical media;On the job training;School (i.e., University, College, etc);Coding Bootcamp;Friend or family member                                                                             1
Books / Physical media;On the job training;Other online resources (e.g., videos, blogs, forum, online community);Online Courses or Certification;Friend or family member;Other (please specify):       1
School (i.e., University, College, etc);Coding Bootcamp;Friend or family member                                                                                                                        1
Name: count, Length: 419, dtype: int64

In [26]:
pattern = r';?\s*(Online Courses or Certification)\s*;?'
df["LearnCodeOnline"] = df["LearnCode"].str.extract(pattern)

In [27]:
df["LearnCodeOnline"].value_counts(dropna=False)

LearnCodeOnline
NaN                                35166
Online Courses or Certification    30271
Name: count, dtype: int64

In [28]:
#Ülkelere göre gruplanmış ve Python ile programlama yapan katılımcılar arasında, her ülkede ortalama ve medyan yıllık tazminat (ConvertedCompYearly) ne kadardır?

In [29]:
df.groupby(["Country", "WorkedPython"])["ConvertedCompYearly"].agg(["mean", "median"])

                                                            mean    median
Country                              WorkedPython
Afghanistan                          Python          4543.000000    4768.5
Albania                              Python         56295.000000   56295.0
Algeria                              Python          9053.285714    6230.0
Andorra                              Python        193331.000000  193331.0
Angola                               Python             6.000000       6.0
...                                                          ...       ...
Venezuela, Bolivarian Republic of... Python         21500.000000    7100.0
Viet Nam                             Python         14014.562500   10180.0
Yemen                                Python         10297.333333    5333.0
Zambia                               Python         28123.666667   22803.0
Zimbabwe                             Python         37500.000000   18000.0

[173 rows x 2 columns]

In [30]:
#En yüksek tazminata sahip 5 katılımcının eğitim seviyeleri nelerdir?

In [31]:
df.sort_values("ConvertedCompYearly", ascending=False)[["EdLevel", "ConvertedCompYearly"]].head()

                                              EdLevel  ConvertedCompYearly
15837    Bachelor’s degree (B.A., B.S., B.Eng., etc.)           16256603.0
12723  Professional degree (JD, MD, Ph.D, Ed.D, etc.)           13818022.0
28379  Professional degree (JD, MD, Ph.D, Ed.D, etc.)            9000000.0
17593    Bachelor’s degree (B.A., B.S., B.Eng., etc.)            6340564.0
17672  Professional degree (JD, MD, Ph.D, Ed.D, etc.)            4936778.0

In [32]:
#Her yaş grubunda Python ile programlama yapan katılımcıların yüzdesi nedir?

In [33]:
df.groupby("Age")["WorkedPython"].value_counts(dropna=False)
grouped = df.groupby("Age")["WorkedPython"].value_counts(normalize=True, dropna=False).round(4) * 100
grouped

Age                 WorkedPython
18-24 years old     Python          55.92
                    NaN             44.08
25-34 years old     NaN             54.23
                    Python          45.77
35-44 years old     NaN             58.48
                    Python          41.52
45-54 years old     NaN             58.09
                    Python          41.91
55-64 years old     NaN             59.57
                    Python          40.43
65 years or older   NaN             62.44
                    Python          37.56
Prefer not to say   NaN             54.66
                    Python          45.34
Under 18 years old  Python          64.88
                    NaN             35.12
Name: proportion, dtype: float64

In [34]:
#Yıllık tazminatı en yüksek %25'lik dilimde olan ve uzaktan çalışan kişilerin yer aldığı en yaygın endüstriler nelerdir?

en_yuksek_25 = df["ConvertedCompYearly"].quantile(0.75)
en_yuksek_25

107971.5

In [35]:
df_en_yuksek_25 = df[df["ConvertedCompYearly"] >= en_yuksek_25]
df_en_yuksek_25

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat,WorkedPython
389,390,I am a developer by profession,25-34 years old,"Employed, full-time;Student, part-time",Remote,Apples,Hobby;School or academic work,Some college/university study without earning ...,Books / Physical media;Colleague;On the job tr...,NaN,...,30.0,5.0,20.0,10.0,5.0,Too long,Easy,110000.0,10.0,Python
392,393,I am a developer by profession,35-44 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Books / Physical media,NaN,...,5.0,10.0,0.0,0.0,5.0,Appropriate in length,Neither easy nor difficult,161044.0,7.0,Python
395,396,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;On the job training;Oth...,NaN,...,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,121018.0,NaN,Python
398,399,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Other (please specify):,Some college/university study without earning ...,Books / Physical media;Colleague;On the job tr...,NaN,...,10.0,30.0,0.0,0.0,0.0,Appropriate in length,Easy,195000.0,5.0,NaN
414,415,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",NaN,...,NaN,NaN,NaN,NaN,NaN,Too long,Easy,184712.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41163,41164,I am a developer by profession,35-44 years old,"Employed, full-time",In-person,Apples,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Online Courses or Certification,...,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,124000.0,NaN,Python
41165,41166,I am a developer by profession,55-64 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,I don’t code outside of work,Some college/university study without earning ...,Books / Physical media;On the job training;Oth...,NaN,...,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,120000.0,NaN,NaN
41184,41185,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Freel...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Other online resources ...,NaN,...,10.0,20.0,15.0,0.0,0.0,Appropriate in length,Easy,170000.0,9.0,NaN
41185,41186,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Other (please specify):,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",NaN,...,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,116844.0,NaN,Python
41187,41188,I am a developer by profession,55-64 years old,"Employed, full-time;Independent contractor, fr...","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Boots...,Something else,Books / Physical media;Colleague;On the job tr...,Online Courses or Certification,...,10.0,10.0,10.0,5.0,5.0,Appropriate in length,Neither easy nor difficult,222834.0,10.0,NaN

In [36]:
df_en_yuksek_25[df_en_yuksek_25["RemoteWork"] == "Remote"]

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat,WorkedPython
389,390,I am a developer by profession,25-34 years old,"Employed, full-time;Student, part-time",Remote,Apples,Hobby;School or academic work,Some college/university study without earning ...,Books / Physical media;Colleague;On the job tr...,NaN,...,30.0,5.0,20.0,10.0,5.0,Too long,Easy,110000.0,10.0,Python
395,396,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;On the job training;Oth...,NaN,...,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,121018.0,NaN,Python
398,399,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Other (please specify):,Some college/university study without earning ...,Books / Physical media;Colleague;On the job tr...,NaN,...,10.0,30.0,0.0,0.0,0.0,Appropriate in length,Easy,195000.0,5.0,NaN
414,415,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",NaN,...,NaN,NaN,NaN,NaN,NaN,Too long,Easy,184712.0,NaN,NaN
416,417,I am a developer by profession,35-44 years old,"Employed, full-time;Independent contractor, fr...",Remote,Apples,Contribute to open-source projects;Freelance/c...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Other online resources ...,Online Courses or Certification,...,15.0,20.0,20.0,15.0,0.0,Too long,Neither easy nor difficult,170000.0,8.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41141,41142,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Apples,Bootstrapping a business;Professional developm...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;On the job training;Oth...,NaN,...,0.0,20.0,0.0,0.0,0.0,Too long,Easy,220000.0,8.0,Python
41142,41143,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Professional development or self-paced l...,Some college/university study without earning ...,Books / Physical media;Other online resources ...,NaN,...,5.0,5.0,10.0,5.0,0.0,Appropriate in length,Easy,200000.0,9.0,Python
41149,41150,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",On the job training;Other online resources (e....,NaN,...,20.0,0.0,15.0,0.0,0.0,Too long,Easy,145000.0,3.0,Python
41165,41166,I am a developer by profession,55-64 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,I don’t code outside of work,Some college/university study without earning ...,Books / Physical media;On the job training;Oth...,NaN,...,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,120000.0,NaN,NaN
41185,41186,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Other (please specify):,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",NaN,...,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,116844.0,NaN,Python

In [37]:
df_en_yuksek_25.groupby([df_en_yuksek_25["RemoteWork"] == "Remote"])["Industry"].value_counts(dropna=False)

RemoteWork  Industry
False       NaN                                           895
            Software Development                          579
            Other:                                        243
            Fintech                                       153
            Banking/Financial Services                    151
            Internet, Telecomm or Information Services    108
            Government                                    107
            Manufacturing                                 103
            Healthcare                                     96
            Retail and Consumer Services                   89
            Computer Systems Design and Services           66
            Transportation, or Supply Chain                60
            Media & Advertising Services                   44
            Energy                                         42
            Higher Education                               29
            Insurance                                      27
True        NaN                                           944
            Software Development                          768
            Other:                                        239
            Healthcare                                    156
            Fintech                                       156
            Internet, Telecomm or Information Services    145
            Retail and Consumer Services                  106
            Media & Advertising Services                  103
            Government                                     69
            Banking/Financial Services                     69
            Computer Systems Design and Services           69
            Transportation, or Supply Chain                67
            Insurance                                      50
            Manufacturing                                  48
            Higher Education                               42
            Energy                                         36
Name: count, dtype: int64